### ISSUE TITLE
Add Travis-CI configuration  to colab-noosfero-plugin repository

### ISSUE THREAD

**Issue by macartur** [colab/colab-noosfero-plugin#22]
It's necessary to have permissions to add colab-noosfero-plugin repository into Travis-CI.

**Comment by macartur** [comment]
@seocam , can you help us on this issue?

**Comment by Ziul** [comment]
#27 and #28 working on it.

**Comment by seocam** [comment]
@macartur sorry for taking that long. I've missed the email :(

**Comment by macartur** [comment]
ok , no problem.
